# Generated by Django 4.2.1 on 2023-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=100)),
                ("market_cap", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("circulating_supply", models.CharField(max_length=100)),
                ("volume", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
